name: Auto-merge
on:
  workflow_run:
    workflows: [Build]
    branches: [auto-merge]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Show git config
        run: git config list --local
      - name: Push current head to main. FF-only
        run: git push origin HEAD:main

