name: Auto-merge
on:
  workflow_run:
    workflows: [Build]
    branches: [auto-merge]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Fetch new commits - fetch refs
        run: git remote set-branches origin '*'
      - name: Fetch commits to shallow clone
        run: git fetch --shallow-since="`git show --no-patch --format=%ci origin/main`"
      - name: Push current head to main
        run: git push -v origin HEAD:main

